name: Run Store Crawlers

on:
  workflow_dispatch:
    inputs:
      run_option:
        description: 'Select which crawler to run'
        required: true
        default: 'all'
        type: choice
        options:
          - seven_eleven
          - family_mart
          - all
      run_meilisearch_indexing:
        description: 'Run Meilisearch indexing job'
        required: true
        default: false
        type: boolean


env:
  FAMILY_MART_KEY: ${{ secrets.FAMILY_MART_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MEILISEARCH_URL: ${{ secrets.MEILISEARCH_URL }}
  MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Initialization Script
        run: python -m init

  seven_eleven_crawler:
    if: ${{ github.event.inputs.run_option == 'seven_eleven' || github.event.inputs.run_option == 'all' }}
    needs: initialize
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Seven Eleven Crawler
        run: python -m seven_eleven.stores_crawler

  family_mart_crawler:
    if: ${{ github.event.inputs.run_option == 'family_mart' || github.event.inputs.run_option == 'all' }}
    needs: initialize
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Family Mart Crawler
        run: python -m family_mart.stores_crawler

  meilisearch_indexing:
    if: ${{ github.event.inputs.run_meilisearch_indexing }}
    needs: [family_mart_crawler, seven_eleven_crawler]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Embedding Script
        run: python -m meilisearch.indexing
